name: Test environment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test_env
    
    steps:
      - name: Run Tests
        id: test_run
        env:
          SECRET_ENV: ${{ secrets.SECRET_KEY }}
        run: echo $SECRET_ENV
