name: Dispatcher

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 4 * * 0-6'

jobs:
  build:
    name: Dispatch Repo
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_DISPATCH_TOKEN }}

    steps:
      - name: Do Something Based On Triggered Event Data
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              --request POST \
              --data '{"event_type": "do-something", "client_payload": { "text": "CROC"}}' \
              https://api.github.com/repos/isandratskiy/github-actions-drafts/dispatches
