name: Repository Dispatch Example

on:
  repository_dispatch:
    types: do-something

jobs:
  build:
    name: Run Some Scheduled Thing

    runs-on: ubuntu-latest

    steps:
      - name: Triggered By Repo Dispathcer
        run: |
         echo "Triggered event text: ${{ github.event.client_payload.text }}"
         echo "${{ github.event_name }}"
         echo "${{ github.event_type }}"
         
