name: Retry Dispatcher

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Retry Dispatch Repo
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_DISPATCH_TOKEN }}

    steps:
      - name: Success
        id: retry_success
        uses: nick-invision/retry@v2
        with:
         max_attempts: 2
         timeout_minutes: 1
         retry_wait_seconds: 1
         retry_on: error
         command: |
           curl -f -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               --request POST \
               --data '{"event_type": "do-something", "client_payload": { "text": "CROC"}}' \
               https://api.github.com/repos/isandratskiy/github-actions-drafts/dispatches

      - name: Failure
        id: retry_failure
        uses: nick-invision/retry@v2
        with:
          max_attempts: 2
          timeout_minutes: 1
          retry_wait_seconds: 1
          retry_on: error
          command: |
            curl -f -H "Accept: application/vnd.github.everest-preview+json" \
                -H "Authorization: Bearer $GH_TOK" \
                --request POST \
                --data '{"event_type": "do-something", "client_payload": { "text": "CROC"}}' \
                https://api.github.com/repos/isandratskiy/github-actions-drafts/dispatches

      - name: Check Success
        uses: nick-invision/assert-action@v1
        if: always()
        with:
          expected: success
          actual: ${{ steps.retry_success.outcome }}

      - name: Check Failure
        uses: nick-invision/assert-action@v1
        if: always()
        with:
          expected: failure
          actual: ${{ steps.retry_failure.outcome }}
