name: Timestamp

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Retry Dispatch Repo
    runs-on: ubuntu-latest

    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
